In [1]:
# import numpy
# create array x
import numpy as np

x = np.array([10,22,32,42,52,62,72,82,92])

In [2]:
# print the shape of x
print x.shape

(9,)


In [3]:
# create a two dimensional array
y = np.array([[21,22,23],
              [24,25,26],
              [27,28,29],
              [210,211,212]])

In [4]:
# print shape of 2d array
print y.shape

(4, 3)


In [5]:
# reshape the array to 2 x 6
y = np.reshape(y,(2,6))
print y

[[ 21  22  23  24  25  26]
 [ 27  28  29 210 211 212]]


In [6]:
# reshape the array to 1 x 12
y = np.reshape(y,(1,12))
print y

[[ 21  22  23  24  25  26  27  28  29 210 211 212]]


In [7]:
# transpose the array
y = np.transpose(y)
print y

[[ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [210]
 [211]
 [212]]


In [8]:
# indexing method 1
#find the 5th value


print y[4]

[25]


In [9]:
# indexing method 2
#find the 2nd to the last value
print y[-2]

[211]


In [10]:
# indexing method 3
#find the element 2 to 5 (starting at 0)

print y[1:4,0]
print y

[22 23 24]
[[ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [210]
 [211]
 [212]]


In [11]:
y

array([[ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [210],
       [211],
       [212]])

In [12]:
# indexing method 4
#find the elements 1,2,3 and 6, (try to index using an array)
#ary = np.array([y[0:3],y[5]])

ary = np.array([0, 1, 2, 5])
print y[ary,0]


[21 22 23 26]


In [13]:
# indexing method 5
#find values in x > 4

print x, "\n"
print x[x> 4]

[10 22 32 42 52 62 72 82 92] 

[10 22 32 42 52 62 72 82 92]


In [14]:
# indexing method 6

threeD = np.reshape(y,(2,3,2))
print threeD


[[[ 21  22]
  [ 23  24]
  [ 25  26]]

 [[ 27  28]
  [ 29 210]
  [211 212]]]


In [15]:
# indexing method 1
#find the 5th value
print threeD[0][2,0]

25


In [16]:
# indexing method 2
#find the 2nd to the last value
print threeD[1][-1][-2]

211


In [41]:
# indexing method 3
#find the element 2 to 5 (starting at 0)

print threeD[0][1:6]

[[23 24]
 [25 26]]


In [42]:
# indexing method 5
#find values in x > 4
print threeD[threeD >4]

[ 21  22  23  24  25  26  27  28  29 210 211 212]
